# Generated by Django 3.1.1 on 2020-09-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('total_quota', models.PositiveIntegerField(default=0)),
                ('total_hours_analysed', models.PositiveIntegerField(default=0)),
                ('ceretai_user', models.BooleanField(default=False)),
                ('test_user', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('current_quota', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('project', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainquickapi.user')),
            ],
        ),
    ]
