# Generated by Django 3.1.1 on 2020-09-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainquickapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='user_id',
            new_name='user',
        ),
    ]
