# Generated by Django 3.1.1 on 2020-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainquickapi', '0002_auto_20200912_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('strict', 'strict'), ('public', 'public')], default='strict', max_length=50)),
            ],
        ),
    ]
