# Generated by Django 3.1.1 on 2020-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
