# Generated by Django 3.1.1 on 2020-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200913_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
