# Generated by Django 3.1.1 on 2020-09-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200914_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agemale',
            old_name='avg_age_f',
            new_name='avg_age_m',
        ),
    ]
